#account_registration:
#   pattern:  /registration
#   defaults: { _controller: AcmeAccountBundle:Account:registration }

account_create:
   pattern:  /registration/create
   defaults: { _controller: AcmeAccountBundle:Account:create }
