parameters:
#    acme_front.example.class: Acme\FrontBundle\Example

services:
#    acme_front.example:
#        class: %acme_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
