parameters:
#    acme_entity.example.class: Acme\EntityBundle\Example

services:
#    acme_entity.example:
#        class: %acme_entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
